import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "../styles/Home.module.css";
import Hero from "../sections/Hero";
import About from "../sections/About";
import Journeys from "../sections/Journeys";

export default function Home() {
  return (
    <>
      <Head>
        <title>Cosmos Adventure</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link
          href="https://fonts.googleapis.com/css2?family=Bungee+Shade&family=Silkscreen:wght@700&display=swap"
          rel="stylesheet"
        />
      </Head>
      <main className="main overflow-x-hidden">
        <Hero />
        <About />
        <Journeys />
      </main>
    </>
  );
}
